### ISSUE TITLE
Iterate

### ISSUE THREAD

**Issue by sm2017** [lemire/FastPriorityQueue.js#10]
How can I iterate over queue? I have a scenario when I lost connection I must iterate over queue and remove some items (Not all)

**Comment by lemire** [comment]
Can you elaborate?

Some pointers:

- If you call pop until the queue is empty, you'll have gone through all elements.
- The underlying data structure is a binary heap. Make sure you are aware of what a binary heap is... and make sure it meets your needs.

**Comment by sm2017** [comment]
I have `object={ priority:integer , durable:boolean}` , I add object to queue and poll it when I need 
Sometimes , I must get and remove all objects with `durable=false` from queue , How can I do this?

**Comment by lemire** [comment]
Create two priority queues, one for durable elements and one for those that aren't durable. Instead of polling just one queue, peek two queues, polling the best one. When you add elements, make sure they get added to the right queue.

**Comment by sm2017** [comment]
@lemire but it is not solution because each time I just peek one item from queue and if I have two queue it is not clear that with queue has priority

**Comment by lemire** [comment]
If you can write better approach, please issue a pull request.
