### ISSUE TITLE
Problem with npm dependency in published package

### ISSUE THREAD

**Issue by sangaman** [lemire/FastPriorityQueue.js#17]
The latest publish to npm has a dependency on the npm package itself, which is causing our travis builds to fail. This is peculiar, because `npm` is not listed as a dependency anywhere in package.json or package-lock.json. Could you make sure that you don't have npm installed locally in the FastPriorityQueue.js folder and try publishing again, 0.6.1 I guess?

See here: https://www.npmjs.com/package/fastpriorityqueue. Previous versions did not have the npm dependency, and I don't think it should've been introduced in #16 because the dependencies in package.json did not change and it published correctly to here: https://www.npmjs.com/package/@exchangeunion/fastpriorityqueue.

Thanks.

**Comment by lemire** [comment]
Here is what I did....

```
npm version 0.6.1
npm publish
```

See if it fixed the problem.

I'll need to read up at some point as to how ``npm`` infers dependencies. I stupidly assumed that it picked them up from ``package.json``. Clearly it is not that simple.

**Comment by sangaman** [comment]
That fixed it! 0 dependencies shown in npm now. I also don't understand why this happened in the first place, I would've assumed package.json and/or package-lock.json.

**Comment by lemire** [comment]
@sangaman  I do recall that hitting ``npm publish`` gave me ``404 error...`` last time. I had to insist.
