### ISSUE TITLE
Peek returns data when size is 0

### ISSUE THREAD

**Issue by jvilk** [lemire/FastPriorityQueue.js#2]
``` js
var FastPriorityQueue = require('fastpriorityqueue');
var q = new FastPriorityQueue();
q.add(1);
q.poll(); // 1
q.size; // 0
q.peek(); // Should be undefined, but is 1
```

**Comment by jvilk** [comment]
Also, you really need to overwrite elements in the array after a `poll` so the garbage collector releases memory. I'm using objects in my priority queue, not numbers.

**Comment by lemire** [comment]
Thanks. I have updated the documentation:

https://github.com/lemire/FastPriorityQueue.js/commit/291b6333cd7fe24987c2304aa2d3554044483576

To recover memory, please call the `trim` function.

The `poll` and `peek` functions assume that either you have checked whether the container is empty (by calling `isEmpty`), or you know it is not empty. You can get the result you apparently desire by the expression `isEmpty() ? undefined : peek()`.

**Comment by lemire** [comment]
As of version 0.2.2, if you call ``poll`` or ``peek`` on an empty queue, you get the undefined value.
