### ISSUE TITLE
the data is rearrange after poll() when the values are all the same

### ISSUE THREAD

**Issue by papayaah** [lemire/FastPriorityQueue.js#3]
probably because this how priority queues are?

example that i put in these data:

{ name: 'a', no: 1}, { name: 'b', no: 1}, { name: 'c', no: 1}

what happens is after a call to poll() - it will pop "a" but the next in the queue would be "c" ?

**Comment by lemire** [comment]
Can you explain what you'd like the code to do with these 3 objects? It is unclear to me what you are tring to do.

**Comment by papayaah** [comment]
i'm using this for a turn based battle game i'm making. here's a complete example:

```
  var fastQueue = new FastPriorityQueue(function(a, b) {
      return a.energy > b.energy;
    });
    [{ name: 'player', energy: 10},
    { name: 'monster1', energy: 10},
    { name: 'monster2', energy: 10},
    { name: 'monster3', energy: 10}
    ].forEach(function(o){
      fastQueue.add(o);
    })
```

and the result is like so:

```
fastQueue.poll()
Object {name: "player", energy: 10}
fastQueue.poll()
Object {name: "monster3", energy: 10}
fastQueue.poll()
Object {name: "monster2", energy: 10}
fastQueue.poll()
Object {name: "monster1", energy: 10}
```

but i would expect for each call to poll, if it's the same shouldn't it at least return the order they were added?

**Comment by papayaah** [comment]
the reason is i visually show the content of the queue after it was created.  which will show the correct sequence. 

but when they get re-order like this after a call to poll, the expectation of the order of the queue is gone.

**Comment by lemire** [comment]
Ok. This is interesting.

**Comment by lemire** [comment]
>  if it's the same shouldn't it at least return the order they were added?

I gave it some thought, and no, you can't expect a heap to preserve insertion order. I think you will find that no queue supports this in practice... 

While thinking about it, I came across this discussion...

http://cstheory.stackexchange.com/questions/593/is-there-a-stable-heap

I know some of these folks and they are quite smart and they say it is not possible to get the desired result without using a whole other data structure.

**Comment by papayaah** [comment]
interesting. I was under the impression this should at least behave like a FIFO since it's still a queue but i guess the algorithm makes it impossible to behave that way. Thanks for your insights.

**Comment by lemire** [comment]
@mickeyren  Turns out that it is a trivial problem to solve. I created a new version of the code for it...

https://github.com/lemire/StablePriorityQueue.js

The API and performance may differ. There is an overhead due to tracking the insertion order.

**Comment by papayaah** [comment]
@lemire appreciate the changes! 

Am i correct to say that when a call to `poll` is made - it doesn't fix the arrangement of the values in the member variable `array` - in fact it kinda messes them up.

I'm asking this because i visually show the content with:
```
for(let i = 0; i < stableQueue.array.length; i++) {
    console.log(stableQueue.array[i].value.name, stableQueue.array[i].value.energy);
}
```
and they definitely get messed up right after a call to `poll`. 

is there anyway i could pull in the contents of the quue in their correct order after a call to poll() ?

here is an example to illustrate my problem:
```
    x = new StablePriorityQueue(function(a, b) {
          return a.energy - b.energy;
    });
    [{ name: 'player', energy: 10},
     { name: 'monster1', energy: 10},
     { name: 'monster2', energy: 10},
     { name: 'monster3', energy: 10}
    ].forEach(function(o){
          x.add(o);
    })
    x.poll();
    for(let i = 0; i < x.array.length; i++) {
        console.log(x.array[i].value.name, x.array[i].value.energy);
    }
    while (!x.isEmpty()) {
        console.log(x.poll());
    }

monster3 10
monster2 10
monster3 10
// poll definitely pulls in the correct order
Object {name: "monster1", energy: 10}
Object {name: "monster2", energy: 10}
Object {name: "monster3", energy: 10}
```

**Comment by papayaah** [comment]
maybe we can introduce a function - `update` that would update the content of the `array` with the correct order?

**Comment by lemire** [comment]
@mickeyren  I don't understand your comment. What do you mean by "messed up"? It forms an array-based binary heap...

https://www.cs.cmu.edu/~adamchik/15-121/lectures/Binary%20Heaps/heaps.html

That's the intended layout.

```
for(let i = 0; i < stableQueue.array.length; i++) {
    console.log(stableQueue.array[i].value.name, stableQueue.array[i].value.energy);
}
```

Don't do this! (Unless you want to have access to the binary heap.)

**Comment by lemire** [comment]
> maybe we can introduce a function - update that would update the content of the array with the correct order?

The backing array, which the users should never look at in actual applications, in organized as a binary heap. We have two functions to maintain the binary heap structure, ``_percolateUp`` and  ``_percolateDown``.

I am not sure what you mean by "correct order".

If you do need the data in sorted order, you need to call poll. As you did there...

```
 while (!x.isEmpty()) {
     console.log(x.poll());
 }
```

**Comment by papayaah** [comment]
Hi @lemire  - i need to show them in advance - the entire contents of the queue, without pulling out something from the list. Unfortunately `peek` only gives me the first one in the queue.

Anything i can use to do that?

**Comment by lemire** [comment]
It is a priority queue, it is not meant to be used to maintain an array in sorted order. You can, of course, poll all of your values out, to a temporary array, and then reinsert them back into the priority queue. It should be quite fast.

**Comment by papayaah** [comment]
thanks @lemire i'll do that instead! Really appreciate!

**Comment by lemire** [comment]
Doing so should be O(n log n). So it should scale well.
