### ISSUE TITLE
"removeMany" fails to iterate over similarly weighted values

### ISSUE THREAD

**Issue by Barbarrosa** [lemire/FastPriorityQueue.js#30]
Given a tree with the following priority values:
```
    1
  /   \
 1     2
/ \   / \
7 4   2 3
```
If I use traversal state or embedded data (rather than the priority itself) to determine whether I want to remove an object, then relying on `removeMany` for that operation may fail to check some items for removal, particularly when some items share the same priority.

Example, using traversal state:
```javascript
var FastPriorityQueue = require("./FastPriorityQueue.js");

var saw2 = false;
var removed2 = false;

var fpq = new FastPriorityQueue();

[1,1,2,7,4,2,3].forEach(e => fpq.add(e));

fpq.removeMany(v => {
  console.log(v); // prints numbers in following order - 1,1,2,7,4,2,1,7,4,2
  if (v === 3) return true;
  if (removed2 || v !== 2) return false;
  if (!saw2) {
    saw2 = true;
    return false;
  }
  removed2 = true;
  return true;
});
fpq.trim();

fpq.array; // [ 1, 3, 1, 7, 4, 2 ]
```

The above case never checked for whether we should remove 3, so it remains in the priority queue.

**Comment by lemire** [comment]
Thanks for your report. I have updated the documentation to indicate the callback function should be a pure function. It was an implicit assumption that the function was pure.

**Comment by Barbarrosa** [comment]
Not sure this resolves the issue. The callback can be a pure function & cause the same issue if you're putting objects in the tree and using a different property to prioritize vs. remove.

**Comment by lemire** [comment]
@Barbarrosa I would invite you to provide a unit test to illustrate the issue, and if at all possible, to consider providing a pull request.

**Comment by Barbarrosa** [comment]
@lemire Done and done. Please see #31 for the unit test and fix which addresses this issue.
