### ISSUE TITLE
The poll method always returns the first item in the internal array

### ISSUE THREAD

**Issue by vjancik** [lemire/FastPriorityQueue.js#4]
This behavior is incorrect if the queue is empty.

If it's empty it ideally should return null, or some other predefined "no element" response.

Current behavior is confusing, wouldn't you agree?

**Comment by lemire** [comment]
Adding duplicate checks is inefficient. The code is *explicit* in its documentation about your responsibility as a caller. You have to call ``isEmpty`` before calling ``poll``. If you prefer to get ``undefined`` when the queue is empty instead of having to call ``isEmpty``, you can get this result  by calling ``isEmpty() ? undefined : poll()``.  


```
// This function assumes that the priority queue is
// not empty and the caller is resposible for the check.
// You can use an expression such as
// "isEmpty() ? undefined : peek()"
// if you expect to be calling peek on an empty priority queue.
//

...

// This function assumes that the priority queue is
// not empty, and the caller is responsible for the check.
// You can use an expression such as
// "isEmpty() ? undefined : poll()"
// if you expect to be calling poll on an empty priority queue.
```

**Comment by vjancik** [comment]
Can't you just put `if(this.size == 0) return null;` at the beginning of that function?

If you need to call the `isEmpty` function anyway, why not just include it in those functions? It's one thing to have fast performing priority queue, it's another thing to have an API that is actually consistent, with how the data structure should function.

**Comment by lemire** [comment]
Can you give me the code sequence you'd like to be able to use?

**Comment by lemire** [comment]
@vjancik  As of version 0.2.2, if you call ``poll`` or ``peek`` on an empty queue, you get the undefined value.
