### ISSUE TITLE
The engine "node" is incompatible with this module. Expected version "~0.4".

### ISSUE THREAD

**Issue by sm2017** [lemire/FastPriorityQueue.js#9]
I run the following command
```
yarn add fastpriorityqueue

error queue-priority@1.0.0: The engine "node" is incompatible with this module. Expected version "~0.4".
error Found incompatible module
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

I see that in https://github.com/lemire/FastPriorityQueue.js/blob/master/package.json#L26-L35 `"queue-priority": "^1.0.0"` is dependency but it is not really dependency it is used only in benchmark

Can you please remove all from dependencies and add it to benchmark folder only ?

**Comment by lemire** [comment]
Yes, I will do so today.

**Comment by lemire** [comment]
Hopefully resolved with the latest release.
